# Text Preprocessing - Information Retrieval
**Topik:** Manajemen Energi  
**Pipeline:** Case Folding → Tokenisasi → Stop-word Removal → Stemming → Forward Index → Inverted Index → Boolean Retrieval

## 1. Import Library

In [7]:
pip install PySastrawi

Requirement already satisfied: PySastrawi in c:\Users\Rio octavian M\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import re
import pandas as pd
from collections import defaultdict
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

## 2. Load Data dari CSV

In [9]:
import pandas as pd
import os

# Read CSV file
df = pd.read_csv('TKI_Keyword_Manajemen Energi(Jurnal).csv')
print(f'File "Manajemen_Energi.csv" loaded successfully.')

File "Manajemen_Energi.csv" loaded successfully.

In [10]:
import pandas as pd
import re

def load_sentences(filepath):
    """
    Membaca file CSV dari filepath dan mengekstrak kalimat dari kolom pertama.
    Baris yang merupakan URL atau baris kosong dilewati.
    Tanda kutip pembungkus dan spasi tepi dibersihkan.
    """
    # Read the CSV file
    df = pd.read_csv(filepath, encoding='utf-8-sig')
    sentences = []

    # Ambil kolom pertama
    for index, row in df.iterrows():
        line = str(row.iloc[0]).strip()
        if not line or pd.isna(line) or line == 'nan': # Skip empty or NaN lines
            continue
        
        # Skip URL
        if line.startswith('http'):
            continue

        # Menghapus tanda kutip pembungkus jika ada
        if line.startswith('"') and line.endswith('"'):
            line = line[1:-1]
        
        line = line.strip()
        if len(line) > 10:
            sentences.append(line)

    return sentences


filepath = 'TKI_Keyword_Manajemen Energi(Jurnal).csv'
sentences = load_sentences(filepath)

print(f'Total kalimat dimuat: {len(sentences)}')
print()
for i, s in enumerate(sentences[:3], 1):
    print(f'[{i}] {s[:90]}...')

Total kalimat dimuat: 58

[1] Tujuan dari penelitian ini adalah untuk mengeksplorasi dampak Akuntansi hijau terhadap kin...
[2] Penelitian sebelumnya menunjukkan bahwa ketika efisiensi energi dianggap strategis, perusa...
[3] Aspek lain dari manajemen energi telah berkembang dari efisiensi biaya murni menjadi efisi...

## 3. Definisi Stop-word

In [11]:
STOPWORDS = {
    # Kata tugas umum
    'yang', 'adalah', 'ini', 'itu', 'untuk', 'dari', 'ke', 'di', 'pada', 'dengan',
    'tidak', 'juga', 'telah', 'oleh', 'dan', 'atau', 'dalam', 'bahwa', 'dapat',
    'akan', 'lebih', 'sudah', 'harus', 'ada', 'saja', 'jika', 'agar', 'atas',
    'bagi', 'antara', 'namun', 'maka', 'karena', 'sehingga', 'secara', 'seperti',
    'sesuai', 'masih', 'belum', 'bisa', 'semua', 'setiap', 'sangat', 'serta',
    'melalui', 'tetapi', 'hingga', 'saat', 'ketika', 'setelah', 'sebelum',
    'selama', 'selain', 'memiliki', 'menjadi', 'sebagai', 'suatu', 'sebuah',
    'hal', 'cara', 'lain', 'maupun', 'merupakan', 'mengenai', 'tersebut',
    'beberapa', 'berbagai', 'terhadap', 'kepada', 'tentang', 'salah', 'satu',
    'jadi', 'bukan', 'terdapat', 'berdasarkan', 'menurut', 'paling', 'hanya',
    'bahkan', 'hampir', 'pula', 'pasti', 'tentu', 'sering', 'selalu',
    # Kata ganti
    'ia', 'dia', 'mereka', 'kami', 'kita', 'saya', 'anda', 'kamu',
    # Preposisi dan konjungsi tambahan
    'dimana', 'per', 'masing', 'sendiri', 'tiap', 'sekaligus', 'kemudian',
    'selanjutnya', 'akhirnya', 'terkait', 'berkaitan', 'terus',
    # Noise domain
    'iot', 'sni', 'kwh', 'rsud', 'smk', 'umkm', 'gambar', 'tabel',
    'google', 'pubmed', 'sciencedirect', 'garuda', 'scholar',
    'internet', 'things', 'al', 'et', 'no',
    # Kata kerja generik
    'menunjukkan', 'menyatakan', 'menjelaskan', 'membahas', 'mengkaji',
    'menelusuri', 'menganalisis', 'merangkum', 'menyimpulkan',
    'dilakukan', 'dilaksanakan', 'diterapkan', 'digunakan', 'diketahui',
    'ditemukan', 'didapatkan', 'diperoleh', 'dikembangkan',
    'bertujuan', 'berfungsi', 'berupa', 'bersifat',
}

print(f'Total stop-word: {len(STOPWORDS)}')

Total stop-word: 146

## 4. Inisialisasi Stemmer (PySastrawi)

In [12]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# Uji stemmer
contoh = ['manajemen', 'penerapan', 'meningkatkan', 'berkelanjutan', 'memediasi']
for kata in contoh:
    print(f'{kata:20s} -> {stemmer.stem(kata)}')

manajemen            -> manajemen
penerapan            -> terap
meningkatkan         -> tingkat
berkelanjutan        -> lanjut
memediasi            -> mediasi

## 5. Fungsi Preprocessing

In [13]:
def case_folding(text):
    """
    Mengubah teks menjadi huruf kecil dan menghapus
    tanda baca, angka, serta karakter non-alfabet.
    """
    text = text.lower()
    text = re.sub(r'\(.*?\)', ' ', text)   # Menghapus isi dalam kurung
    text = re.sub(r'[^a-z\s]', ' ', text)  # Menghapus non-huruf
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def tokenisasi(text):
    """
    Memecah teks menjadi daftar token kata tunggal.
    Token dengan panjang kurang dari 3 karakter dibuang.
    """
    return [t for t in text.split() if len(t) >= 3]


def hapus_stopword(tokens):
    """
    Membuang token yang termasuk dalam daftar stop-word.
    """
    return [t for t in tokens if t not in STOPWORDS]


def stemming(tokens):
    """
    Mengembalikan setiap token ke bentuk kata dasarnya
    menggunakan algoritma Nazief-Adriani via PySastrawi.
    Hasil yang masih termasuk stop-word setelah stemming dibuang.
    """
    hasil = []
    for t in tokens:
        stem = stemmer.stem(t)
        if stem not in STOPWORDS and len(stem) >= 3:
            hasil.append(stem)
    return hasil


def preprocessing(doc_id, raw_text):
    """
    Menjalankan seluruh pipeline preprocessing pada satu kalimat.
    Mengembalikan dictionary dengan setiap tahap sebagai key.
    """
    folded   = case_folding(raw_text)
    tokens   = tokenisasi(folded)
    no_stop  = hapus_stopword(tokens)
    stemmed  = stemming(no_stop)

    return {
        'DocID'             : doc_id,
        'Teks Mentah'       : raw_text.strip(),
        'Case Folding'      : folded,
        'Tokenisasi'        : tokens,
        'Stopword Removal'  : no_stop,
        'Stemming'          : stemmed,
    }

## 6. Preprocessing Seluruh Dokumen

In [14]:
records = []
for i, kalimat in enumerate(sentences, 1):
    record = preprocessing(f'Doc {i}', kalimat)
    records.append(record)

print(f'Total dokumen diproses: {len(records)}')

Total dokumen diproses: 58

## 7. Tabel Preprocessing Lengkap

In [15]:
df_prep = pd.DataFrame(records)

# Kolom tampilan: ubah list menjadi string untuk tabel
df_display = df_prep.copy()
df_display['Tokenisasi']       = df_display['Tokenisasi'].apply(lambda x: ', '.join(x))
df_display['Stopword Removal'] = df_display['Stopword Removal'].apply(lambda x: ', '.join(x))
df_display['Stemming']         = df_display['Stemming'].apply(lambda x: ', '.join(x))

pd.set_option('display.max_colwidth', 60)
pd.set_option('display.max_rows', len(df_display))

df_display[['DocID', 'Teks Mentah', 'Case Folding', 'Tokenisasi', 'Stopword Removal', 'Stemming']]

,DocID,Teks Mentah,Case Folding,Tokenisasi,Stopword Removal,Stemming
0,Doc 1,Tujuan dari penelitian ini adalah untuk mengeksplorasi d...,tujuan dari penelitian ini adalah untuk mengeksplorasi d...,"tujuan, dari, penelitian, ini, adalah, untuk, mengeksplo...","tujuan, penelitian, mengeksplorasi, dampak, akuntansi, h...","tuju, teliti, eksplorasi, dampak, akuntansi, hijau, kerj..."
1,Doc 2,Penelitian sebelumnya menunjukkan bahwa ketika efisiensi...,penelitian sebelumnya menunjukkan bahwa ketika efisiensi...,"penelitian, sebelumnya, menunjukkan, bahwa, ketika, efis...","penelitian, sebelumnya, efisiensi, energi, dianggap, str...","teliti, efisiensi, energi, anggap, strategis, usaha, cen..."
2,Doc 3,Aspek lain dari manajemen energi telah berkembang dari e...,aspek lain dari manajemen energi telah berkembang dari e...,"aspek, lain, dari, manajemen, energi, telah, berkembang,...","aspek, manajemen, energi, berkembang, efisiensi, biaya, ...","aspek, manajemen, energi, kembang, efisiensi, biaya, mur..."
3,Doc 4,"Di sisi lain, diketahui bahwa sistem manajemen energi ma...",di sisi lain diketahui bahwa sistem manajemen energi mam...,"sisi, lain, diketahui, bahwa, sistem, manajemen, energi,...","sisi, sistem, manajemen, energi, mampu, menjamin, kualit...","sisi, sistem, manajemen, energi, mampu, jamin, kualitas,..."
4,Doc 5,Hal ini menunjukkan bahwa sistem manajemen energi memban...,hal ini menunjukkan bahwa sistem manajemen energi memban...,"hal, ini, menunjukkan, bahwa, sistem, manajemen, energi,...","sistem, manajemen, energi, membantu, menyediakan, lingku...","sistem, manajemen, energi, bantu, sedia, lingkung, ruang..."
5,Doc 6,Pengaruh antara akuntansi hijau dan kinerja berkelanjuta...,pengaruh antara akuntansi hijau dan kinerja berkelanjuta...,"pengaruh, antara, akuntansi, hijau, dan, kinerja, berkel...","pengaruh, akuntansi, hijau, kinerja, berkelanjutan, dime...","pengaruh, akuntansi, hijau, kerja, lanjut, mediasi, mana..."
6,Doc 7,Hasil penelitian ini sejalan dengan temuan Rahman dan Is...,hasil penelitian ini sejalan dengan temuan rahman dan is...,"hasil, penelitian, ini, sejalan, dengan, temuan, rahman,...","hasil, penelitian, sejalan, temuan, rahman, islam, manaj...","hasil, teliti, jalan, temu, rahman, islam, manajemen, en..."
7,Doc 8,Manajemen energi dapat memediasi pengaruh akuntansi hija...,manajemen energi dapat memediasi pengaruh akuntansi hija...,"manajemen, energi, dapat, memediasi, pengaruh, akuntansi...","manajemen, energi, memediasi, pengaruh, akuntansi, hijau...","manajemen, energi, mediasi, pengaruh, akuntansi, hijau, ..."
8,Doc 9,Hasil penelitian ini menunjukkan bahwa penerapan akuntan...,hasil penelitian ini menunjukkan bahwa penerapan akuntan...,"hasil, penelitian, ini, menunjukkan, bahwa, penerapan, a...","hasil, penelitian, penerapan, akuntansi, hijau, manajeme...","hasil, teliti, terap, akuntansi, hijau, manajemen, energ..."
9,Doc 10,"Di sisi lain, diketahui bahwa sistem manajemen energi ma...",di sisi lain diketahui bahwa sistem manajemen energi mam...,"sisi, lain, diketahui, bahwa, sistem, manajemen, energi,...","sisi, sistem, manajemen, energi, mampu, menjamin, kualit...","sisi, sistem, manajemen, energi, mampu, jamin, kualitas,..."
10,Doc 11,Hal ini menunjukkan bahwa sistem manajemen energi memban...,hal ini menunjukkan bahwa sistem manajemen energi memban...,"hal, ini, menunjukkan, bahwa, sistem, manajemen, energi,...","sistem, manajemen, energi, membantu, menyediakan, lingku...","sistem, manajemen, energi, bantu, sedia, lingkung, ruang..."
11,Doc 12,"Berdasarkan UMKM di Jawa Timur, akuntansi hijau dan mana...",berdasarkan umkm di jawa timur akuntansi hijau dan manaj...,"berdasarkan, umkm, jawa, timur, akuntansi, hijau, dan, m...","jawa, timur, akuntansi, hijau, manajemen, energi, mening...","jawa, timur, akuntansi, hijau, manajemen, energi, tingka..."
12,Doc 13,Edukasi ini dapat dilakukan melalui penyampaian materi d...,edukasi ini dapat dilakukan melalui penyampaian materi d...,"edukasi, ini, dapat, dilakukan, melalui, penyampaian, ma...","edukasi, penyampaian, materi, praktik, masyarakat, kompe...","edukasi, sampai, materi, praktik, masyarakat, kompetensi..."
13,Doc 14,Edukasi ini juga mendorong ketertarikan peserta untuk me...,edukasi ini juga mendorong ketertarikan peserta untuk me...,"edukasi, ini, juga, mendorong, ketertarikan, peserta, un...","edukasi, mendorong, ketertarikan, peserta, melakukan, in...","edukasi, dorong, tari, laku, inovasi, bidang, teknologi,..."
14,Doc 15,Kegiatan ini berupa praktik audit dan manajemen energi b...,kegiatan ini berupa praktik audit dan manajemen energi b...,"kegiatan, ini, berupa, praktik, audit, dan, manajemen, e...","kegiatan, praktik, audit, manajemen, energi, berbasis, m...","giat, praktik, audit, manajemen, energi, bas, sebar, has..."
15,Doc 16,Pada penelitian yang telah dilakukan mengenai pemanfaata...,pada penelitian yang telah dilakukan mengenai pemanfaata...,"pada, penelitian, yang, telah, dilakukan, mengenai, pema...","penelitian, pemanfaatan, teknologi, rangka, audit, energ...","teliti, manfaat, teknologi, rangka, audit, energi, manaj..."
16,Doc 17,Jika ditemukan adanya indikasi pemborosan atau tidak ses...,jika ditemukan adanya indikasi pemborosan atau tidak ses...,"jika, ditemukan, adanya, indikasi, pemborosan, atau, tid...","adanya, indikasi, pemborosan, standar, tindakan, manajem...","indikasi, boros, standar, tindak, manajemen, energi, per..."
17,Doc 18,Edukasi dalam bentuk praktik langsung merupakan hal yang...,edukasi dalam bentuk praktik langsung merupakan hal yang...,"edukasi, dalam, bentuk, praktik, langsung, merupakan, ha...","edukasi, bentuk, praktik, langsung, tepat, masyarakat, m...","edukasi, bentuk, praktik, langsung, tepat, masyarakat, t..."
18,Doc 19,Analisis pada pretest didapatkan kemampuan awal peserta ...,analisis pada pretest didapatkan kemampuan awal peserta ...,"analisis, pada, pretest, didapatkan, kemampuan, awal, pe...","analisis, pretest, kemampuan, awal, peserta, pelatihan, ...","analisis, pretest, mampu, awal, latih, golong, kurang, u..."
19,Doc 20,Pelatihan ini berupa praktik langsung untuk mengetahui k...,pelatihan ini berupa praktik langsung untuk mengetahui k...,"pelatihan, ini, berupa, praktik, langsung, untuk, menget...","pelatihan, praktik, langsung, mengetahui, konsumsi, ener...","latih, praktik, langsung, tahu, konsumsi, energi, bandar..."
20,Doc 21,"Setelah dilaksanakan pretest, kegiatan selanjutnya pemap...",setelah dilaksanakan pretest kegiatan selanjutnya pemapa...,"setelah, dilaksanakan, pretest, kegiatan, selanjutnya, p...","pretest, kegiatan, pemaparan, materi, audit, manajemen, ...","pretest, giat, papar, materi, audit, manajemen, energi, ..."
21,Doc 22,Selanjutnya dilaksanakan praktik audit dan manajemen ene...,selanjutnya dilaksanakan praktik audit dan manajemen ene...,"selanjutnya, dilaksanakan, praktik, audit, dan, manajeme...","praktik, audit, manajemen, energi, langsung, peserta, pe...","praktik, audit, manajemen, energi, langsung, latih"
22,Doc 23,). Hasil audit energi ini dapat langsung dicetak dan dig...,hasil audit energi ini dapat langsung dicetak dan diguna...,"hasil, audit, energi, ini, dapat, langsung, dicetak, dan...","hasil, audit, energi, langsung, dicetak, referensi, meme...","hasil, audit, energi, langsung, cetak, referensi, memebr..."
23,Doc 24,Kegiatan ini dapat meningkatkan kemampuan peserta dalam ...,kegiatan ini dapat meningkatkan kemampuan peserta dalam ...,"kegiatan, ini, dapat, meningkatkan, kemampuan, peserta, ...","kegiatan, meningkatkan, kemampuan, peserta, melakukan, a...","giat, tingkat, mampu, laku, audit, manajemen, energi, ku..."
24,Doc 25,Dari pelaksanaan kegiatan pelatihan aplikasi teknologi I...,dari pelaksanaan kegiatan pelatihan aplikasi teknologi i...,"dari, pelaksanaan, kegiatan, pelatihan, aplikasi, teknol...","pelaksanaan, kegiatan, pelatihan, aplikasi, teknologi, a...","laksana, giat, latih, aplikasi, teknologi, audit, manaje..."
25,Doc 26,Berdasarkan hasil evaluasi yang dilakukan diketahui bahw...,berdasarkan hasil evaluasi yang dilakukan diketahui bahw...,"berdasarkan, hasil, evaluasi, yang, dilakukan, diketahui...","hasil, evaluasi, peserta, pengetahuan, baru, berhubungan...","hasil, evaluasi, tahu, baru, hubung, teknologi, audit, m..."
26,Doc 27,Penelitian ini bertujuan untuk mengkaji peran manajemen ...,penelitian ini bertujuan untuk mengkaji peran manajemen ...,"penelitian, ini, bertujuan, untuk, mengkaji, peran, mana...","penelitian, peran, manajemen, energi, meningkatkan, efis...","teliti, peran, manajemen, energi, tingkat, efisiensi, ko..."
27,Doc 28,). Penerapan manajemen energi melalui edukasi literasi e...,penerapan manajemen energi melalui edukasi literasi ener...,"penerapan, manajemen, energi, melalui, edukasi, literasi...","penerapan, manajemen, energi, edukasi, literasi, energi,...","terap, manajemen, energi, edukasi, literasi, energi, man..."
28,Doc 29,Manajemen energi menjadi pendekatan strategis yang dapat...,manajemen energi menjadi pendekatan strategis yang dapat...,"manajemen, energi, menjadi, pendekatan, strategis, yang,...","manajemen, energi, pendekatan, strategis, mengelola, kon...","manajemen, energi, dekat, strategis, kelola, konsumsi, l..."
29,Doc 30,Manfaat dari penerapan manajemen energi telah terbukti m...,manfaat dari penerapan manajemen energi telah terbukti m...,"manfaat, dari, penerapan, manajemen, energi, telah, terb...","manfaat, penerapan, manajemen, energi, terbukti, penelit...","manfaat, terap, manajemen, energi, bukti, teliti, prakti..."
30,Doc 31,"Oleh karena itu, perlu dilakukan kajian lebih lanjut unt...",oleh karena itu perlu dilakukan kajian lebih lanjut untu...,"oleh, karena, itu, perlu, dilakukan, kajian, lebih, lanj...","perlu, kajian, lanjut, memahami, bagaimana, manajemen, e...","perlu, kaji, lanjut, paham, bagaimana, manajemen, energi..."
31,Doc 32,"Melalui kajian literatur ini, penulis bertujuan untuk me...",melalui kajian literatur ini penulis bertujuan untuk mer...,"melalui, kajian, literatur, ini, penulis, bertujuan, unt...","kajian, literatur, penulis, temuan, ilmiah, peran, manaj...","kaji, literatur, tulis, temu, ilmiah, peran, manajemen, ..."
32,Doc 33,Kajian literatur dilakukan dengan menelusuri dan mengana...,kajian literatur dilakukan dengan menelusuri dan mengana...,"kajian, literatur, dilakukan, dengan, menelusuri, dan, m...","kajian, literatur, sumber, ilmiah, relevan, jurnal, arti...","kaji, literatur, sumber, ilmiah, relevan, jurnal, artike..."
33,Doc 34,Fokus kajian diarahkan pada studi yang membahas konsumsi...,fokus kajian diarahkan pada studi yang membahas konsumsi...,"fokus, kajian, diarahkan, pada, studi, yang, membahas, k...","fokus, kajian, diarahkan, studi, konsumsi, listrik, kapi...","fokus, kaji, arah, studi, konsumsi, listrik, kapita, per..."
34,Doc 35,Berdasarkan penelusuran jurnal melalui situs seperti Goo...,berdasarkan penelusuran jurnal melalui situs seperti goo...,"berdasarkan, penelusuran, jurnal, melalui, situs, sepert...","penelusuran, jurnal, situs, data, base, jurnal, portal, ...","telusur, jurnal, situs, data, base, jurnal, portal, guna..."
35,Doc 36,"Dalam konteks ini, pemahaman terhadap konsumsi listrik p...",dalam konteks ini pemahaman terhadap konsumsi listrik pe...,"dalam, konteks, ini, pemahaman, terhadap, konsumsi, list...","konteks, pemahaman, konsumsi, listrik, kapita, relevan, ...","konteks, paham, konsumsi, listrik, kapita, relevan, liha..."
36,Doc 37,Data ini berfungsi sebagai indikator penting untuk melih...,data ini berfungsi sebagai indikator penting untuk melih...,"data, ini, berfungsi, sebagai, indikator, penting, untuk...","data, indikator, penting, melihat, sejauh, mana, kebutuh...","data, indikator, penting, lihat, jauh, mana, butuh, ener..."
37,Doc 38,Meningkatkan konsumsi listrik memang menjadi bagian dari...,meningkatkan konsumsi listrik memang menjadi bagian dari...,"meningkatkan, konsumsi, listrik, memang, menjadi, bagian...","meningkatkan, konsumsi, listrik, memang, bagian, proses,...","tingkat, konsumsi, listrik, memang, proses, bangun, irin..."
38,Doc 39,". Oleh karena itu, penerapan manajemen energi di sektor ...",oleh karena itu penerapan manajemen energi di sektor rum...,"oleh, karena, itu, penerapan, manajemen, energi, sektor,...","penerapan, manajemen, energi, sektor, rumah, tangga, kru...","terap, manajemen, energi, sektor, rumah, tangga, krusial"
39,Doc 40,Untuk mengatasi tantangan krisis energi dan terus mening...,untuk mengatasi tantangan krisis energi dan terus mening...,"untuk, mengatasi, tantangan, krisis, energi, dan, terus,...","mengatasi, tantangan, krisis, energi, meningkatnya, kons...","tantang, krisis, energi, tingkat, konsumsi, listrik, rum..."
40,Doc 41,Manajemen energi adalah suatu pendekatan terencana dan s...,manajemen energi adalah suatu pendekatan terencana dan s...,"manajemen, energi, adalah, suatu, pendekatan, terencana,...","manajemen, energi, pendekatan, terencana, sistematis, me...","manajemen, energi, dekat, rencana, sistematis, atur, pan..."
41,Doc 42,"Dalam konteks rumah tangga, manajemen energi memiliki ru...",dalam konteks rumah tangga manajemen energi memiliki rua...,"dalam, konteks, rumah, tangga, manajemen, energi, memili...","konteks, rumah, tangga, manajemen, energi, ruang, lingku...","konteks, rumah, tangga, manajemen, energi, ruang, lingku..."
42,Doc 43,Salah satu langkah awal dalam menerapkan manajemen energ...,salah satu langkah awal dalam menerapkan manajemen energ...,"salah, satu, langkah, awal, dalam, menerapkan, manajemen...","langkah, awal, menerapkan, manajemen, energi, peningkata...","langkah, awal, terap, manajemen, energi, tingkat, litera..."
43,Doc 44,"Di sisi teknis, pengembangan dan penerapan teknologi pin...",di sisi teknis pengembangan dan penerapan teknologi pint...,"sisi, teknis, pengembangan, dan, penerapan, teknologi, p...","sisi, teknis, pengembangan, penerapan, teknologi, pintar...","sisi, teknis, kembang, terap, teknologi, pintar, terobos..."
44,Doc 45,Pemerintah juga memiliki peran penting dalam menciptakan...,pemerintah juga memiliki peran penting dalam menciptakan...,"pemerintah, juga, memiliki, peran, penting, dalam, menci...","pemerintah, peran, penting, menciptakan, iklim, kondusif...","perintah, peran, penting, cipta, iklim, kondusif, implem..."
45,Doc 46,"Selain pendekatan efisiensi, integrasi energi terbarukan...",selain pendekatan efisiensi integrasi energi terbarukan ...,"selain, pendekatan, efisiensi, integrasi, energi, terbar...","pendekatan, efisiensi, integrasi, energi, terbarukan, ba...","dekat, efisiensi, integrasi, energi, baru, solusi, manaj..."
46,Doc 47,keberhasilan manajemen energi tidak dapat dicapai hanya ...,keberhasilan manajemen energi tidak dapat dicapai hanya ...,"keberhasilan, manajemen, energi, tidak, dapat, dicapai, ...","keberhasilan, manajemen, energi, dicapai, pendekatan, te...","hasil, manajemen, energi, capai, dekat, teknologi, bijak..."
47,Doc 48,"Secara keseluruhan, manajemen energi di sektor rumah tan...",secara keseluruhan manajemen energi di sektor rumah tang...,"secara, keseluruhan, manajemen, energi, sektor, rumah, t...","keseluruhan, manajemen, energi, sektor, rumah, tangga, a...","seluruh, manajemen, energi, sektor, rumah, tangga, alat,..."
48,Doc 49,Dengan penerapan solusi-solusi manajemen energi yang ter...,dengan penerapan solusi solusi manajemen energi yang ter...,"dengan, penerapan, solusi, solusi, manajemen, energi, ya...","penerapan, solusi, solusi, manajemen, energi, terstruktu...","terap, solusi, solusi, manajemen, energi, struktur, orie..."
49,Doc 50,Penerapan manajemen energi terbukti mampu menekan pembor...,penerapan manajemen energi terbukti mampu menekan pembor...,"penerapan, manajemen, energi, terbukti, mampu, menekan, ...","penerapan, manajemen, energi, terbukti, mampu, menekan, ...","terap, manajemen, energi, bukti, mampu, tekan, boros, en..."
50,Doc 51,"Dengan demikian, manajemen energi tidak hanya menjawab t...",dengan demikian manajemen energi tidak hanya menjawab ta...,"dengan, demikian, manajemen, energi, tidak, hanya, menja...","demikian, manajemen, energi, menjawab, tantangan, pening...","demikian, manajemen, energi, jawab, tantang, tingkat, bu..."
51,Doc 52,Penelitian tentang manajemen energi dan/atau audit energ...,penelitian tentang manajemen energi dan atau audit energ...,"penelitian, tentang, manajemen, energi, dan, atau, audit...","penelitian, manajemen, energi, audit, energi, banyak, di...","teliti, manajemen, energi, audit, energi, banyak, bagai,..."
52,Doc 53,Efisiensi penggunaan energimasih mungkin ditingkatkan me...,efisiensi penggunaan energimasih mungkin ditingkatkan me...,"efisiensi, penggunaan, energimasih, mungkin, ditingkatka...","efisiensi, penggunaan, energimasih, mungkin, ditingkatka...","efisiensi, guna, energimasih, mungkin, tingkat, terap, s..."
53,Doc 54,Agar dilakukan peninjauan ulang atas semua instalasi/per...,agar dilakukan peninjauan ulang atas semua instalasi per...,"agar, dilakukan, peninjauan, ulang, atas, semua, instala...","peninjauan, ulang, instalasi, peralatan, energi, penerap...","tinjau, ulang, instalasi, alat, energi, terap, manajemen..."
54,Doc 55,Pengoperasian peralatan energi dilakukan dengan prinsip ...,pengoperasian peralatan energi dilakukan dengan prinsip ...,"pengoperasian, peralatan, energi, dilakukan, dengan, pri...","pengoperasian, peralatan, energi, prinsip, manajemen, en...","operasi, alat, energi, prinsip, manajemen, energi"
55,Doc 56,Efisiensi penggunaan energi masih mungkin ditingkatkan m...,efisiensi penggunaan energi masih mungkin ditingkatkan m...,"efisiensi, penggunaan, energi, masih, mungkin, ditingkat...","efisiensi, penggunaan, energi, mungkin, ditingkatkan, pe...","efisiensi, guna, energi, mungkin, tingkat, terap, sistem..."
56,Doc 57,Agar ditinjau ulang atas semua instalasi/peralatan energ...,agar ditinjau ulang atas semua instalasi peralatan energ...,"agar, ditinjau, ulang, atas, semua, instalasi, peralatan...","ditinjau, ulang, instalasi, peralatan, energi, penerapan...","tinjau, ulang, instalasi, alat, energi, terap, manajemen..."
57,Doc 58,Sesuai dengan gambar diatas dapat disampaikan bahwa pemb...,sesuai dengan gambar diatas dapat disampaikan bahwa pemb...,"sesuai, dengan, gambar, diatas, dapat, disampaikan, bahw...","diatas, disampaikan, pembiayaan, energi, listrik, besar,...","sampai, biaya, energi, listrik, besar, persentase, bandi..."

## 8. Forward Index

In [16]:
def buat_forward_index(records):
    """
    Membangun forward index: DocID -> {term: frekuensi}.
    Menghitung frekuensi kemunculan setiap term dalam satu dokumen.
    """
    forward_index = {}
    for rec in records:
        freq = defaultdict(int)
        for term in rec['Stemming']:
            freq[term] += 1
        forward_index[rec['DocID']] = dict(sorted(freq.items()))
    return forward_index


forward_index = buat_forward_index(records)

# Tampilkan sebagai tabel
fi_rows = []
for doc_id, terms in forward_index.items():
    term_freq_str = ', '.join([f'{t}:{f}' for t, f in sorted(terms.items(), key=lambda x: -x[1])])
    fi_rows.append({
        'DocID'              : doc_id,
        'Term : Frekuensi'   : term_freq_str,
        'Jumlah Unique Term' : len(terms),
    })

df_forward = pd.DataFrame(fi_rows)
df_forward

,DocID,Term : Frekuensi,Jumlah Unique Term
0,Doc 1,"akuntansi:1, dampak:1, eksplorasi:1, energi:1, hijau:1, ...",11
1,Doc 2,"energi:2, anggap:1, cenderung:1, efisiensi:1, manajemen:...",10
2,Doc 3,"efisiensi:3, aspek:1, biaya:1, energi:1, kembang:1, kerj...",14
3,Doc 4,"energi:2, beri:1, efisiensi:1, jamin:1, kualitas:1, ling...",11
4,Doc 5,"bantu:1, energi:1, karyawan:1, kualitas:1, langgan:1, li...",12
5,Doc 6,"akuntansi:1, energi:1, hijau:1, kerja:1, lanjut:1, manaj...",8
6,Doc 7,"akuntansi:1, energi:1, hasil:1, hijau:1, islam:1, jalan:...",14
7,Doc 8,"akuntansi:1, energi:1, hijau:1, kerja:1, lingkung:1, man...",8
8,Doc 9,"akuntansi:1, bisnis:1, energi:1, hasil:1, hijau:1, langs...",9
9,Doc 10,"energi:2, beri:1, efisiensi:1, jamin:1, kualitas:1, ling...",11
10,Doc 11,"bantu:1, energi:1, gilir:1, karyawan:1, kualitas:1, lang...",13
11,Doc 12,"akuntansi:1, energi:1, hijau:1, jawa:1, kerja:1, lanjut:...",9
12,Doc 13,"audit:1, bagaimana:1, edukasi:1, efisien:1, energi:1, fu...",14
13,Doc 14,"teknologi:2, audit:1, bas:1, bidang:1, dorong:1, edukasi...",12
14,Doc 15,"energi:3, masyarakat:2, alat:1, audit:1, bas:1, beri:1, ...",22
15,Doc 16,"energi:4, listrik:3, besar:2, digital:2, komponen:2, kon...",17
16,Doc 17,"energi:2, bidang:1, boros:1, dasar:1, elektro:1, indikas...",14
17,Doc 18,"audit:1, bentuk:1, edukasi:1, energi:1, langsung:1, mana...",10
18,Doc 19,"energi:2, analisis:1, audit:1, awal:1, golong:1, kurang:...",12
19,Doc 20,"energi:2, audit:1, awal:1, bandar:1, konsumsi:1, kurang:...",15
20,Doc 21,"abdi:1, audit:1, energi:1, giat:1, manajemen:1, materi:1...",9
21,Doc 22,"audit:1, energi:1, langsung:1, latih:1, manajemen:1, pra...",6
22,Doc 23,"energi:2, audit:1, cetak:1, hasil:1, langsung:1, manajem...",10
23,Doc 24,"audit:1, baik:1, energi:1, giat:1, kurang:1, laku:1, mam...",9
24,Doc 25,"energi:2, aplikasi:1, audit:1, efisiensi:1, giat:1, ikut...",14
25,Doc 26,"audit:1, baru:1, energi:1, evaluasi:1, hasil:1, hubung:1...",9
26,Doc 27,"dekat:1, efisiensi:1, energi:1, konsumsi:1, listrik:1, l...",14
27,Doc 28,"energi:5, terap:2, alat:1, atap:1, baru:1, bas:1, boros:...",25
28,Doc 29,"bijak:1, dekat:1, efisien:1, energi:1, kelola:1, konsums...",9
29,Doc 30,"negara:2, bukti:1, energi:1, hadap:1, implementasi:1, in...",12
30,Doc 31,"bagaimana:1, efektif:1, energi:1, indonesia:1, kaji:1, l...",12
31,Doc 32,"efisiensi:1, energi:1, ilmiah:1, kaji:1, konsumsi:1, lis...",14
32,Doc 33,"energi:2, artikel:1, buku:1, efisiensi:1, ilmiah:1, indo...",22
33,Doc 34,"energi:3, arah:1, bijak:1, efisiensi:1, fokus:1, kaji:1,...",18
34,Doc 35,"energi:3, jurnal:2, baru:1, base:1, data:1, efisiensi:1,...",18
35,Doc 36,"energi:2, waktu:2, butuh:1, dasar:1, dinamika:1, efisien...",18
36,Doc 37,"energi:2, listrik:2, waktu:2, butuh:1, dasar:1, data:1, ...",23
37,Doc 38,"energi:2, bangun:1, boros:1, efektif:1, iring:1, konsums...",15
38,Doc 39,"energi:1, krusial:1, manajemen:1, rumah:1, sektor:1, tan...",7
39,Doc 40,"energi:3, biaya:1, dukung:1, hemat:1, konsumsi:1, krisis...",20
40,Doc 41,"energi:2, guna:2, kurang:2, atur:1, boros:1, dekat:1, ma...",15
41,Doc 42,"bijak:1, dukung:1, efisien:1, energi:1, individu:1, kont...",18
42,Doc 43,"energi:2, awal:1, langkah:1, literasi:1, manajemen:1, ma...",8
43,Doc 44,"energi:1, kembang:1, manajemen:1, pintar:1, rumah:1, sig...",12
44,Doc 45,"cipta:1, energi:1, iklim:1, implementasi:1, kondusif:1, ...",9
45,Doc 46,"energi:2, baru:1, dekat:1, efisiensi:1, integrasi:1, lan...",8
46,Doc 47,"bijak:1, capai:1, dekat:1, energi:1, hasil:1, manajemen:...",8
47,Doc 48,"alat:1, bangun:1, depan:1, energi:1, fondasi:1, konsumsi...",17
48,Doc 49,"energi:2, kurang:2, solusi:2, agenda:1, aktif:1, bangun:...",23
49,Doc 50,"energi:5, alat:1, atap:1, baru:1, boros:1, bukti:1, eduk...",23
50,Doc 51,"energi:2, bangun:1, butuh:1, demi:1, demikian:1, dukung:...",19
51,Doc 52,"bidang:4, energi:2, audit:1, bagai:1, banyak:1, didik:1,...",10
52,Doc 53,"efisiensi:1, energi:1, energimasih:1, guna:1, manajemen:...",9
53,Doc 54,"energi:2, alat:1, bangun:1, instalasi:1, kelola:1, manaj...",9
54,Doc 55,"energi:2, alat:1, manajemen:1, operasi:1, prinsip:1",5
55,Doc 56,"energi:2, efisiensi:1, guna:1, manajemen:1, mungkin:1, p...",9
56,Doc 57,"energi:2, alat:1, bangun:1, instalasi:1, kelola:1, manaj...",9
57,Doc 58,"energi:3, bahas:1, banding:1, besar:1, biaya:1, denga:1,...",14

## 9. Inverted Index

In [17]:
def buat_inverted_index(records):
    """
    Membangun inverted index: term -> [DocID, ...].
    Setiap term dipetakan ke daftar dokumen yang mengandungnya.
    """
    inverted = defaultdict(list)
    for rec in records:
        for term in set(rec['Stemming']):
            inverted[term].append(rec['DocID'])

    # Urutkan dictionary dan posting list
    inverted_sorted = {}
    for term in sorted(inverted.keys()):
        posting = sorted(inverted[term], key=lambda x: int(x.split()[1]))
        inverted_sorted[term] = posting

    return inverted_sorted


inverted_index = buat_inverted_index(records)

# Tampilkan sebagai tabel
ii_rows = []
for i, (term, posting) in enumerate(inverted_index.items(), 1):
    ii_rows.append({
        'No'          : i,
        'Kata Dasar'  : term,
        'Posting List': ', '.join(posting),
        'df'          : len(posting),
    })

df_inverted = pd.DataFrame(ii_rows)
print(f'Total term unik: {len(df_inverted)}')
df_inverted

Total term unik: 268

,No,Kata Dasar,Posting List,df
0,1,abdi,Doc 21,1
1,2,agenda,Doc 49,1
2,3,aktif,Doc 49,1
3,4,akuntansi,"Doc 1, Doc 6, Doc 7, Doc 8, Doc 9, Doc 12",6
4,5,alat,"Doc 15, Doc 28, Doc 48, Doc 50, Doc 54, Doc 55, Doc 57",7
...,...,...,...,...
263,264,usaha,Doc 2,1
264,265,utama,"Doc 16, Doc 19, Doc 20",3
265,266,waktu,"Doc 28, Doc 36, Doc 37",3
266,267,wawas,Doc 48,1
267,268,web,Doc 33,1

## 10. Boolean Retrieval

In [18]:
def get_posting(term):
    """
    Mengambil posting list untuk satu term.
    Term di-stem terlebih dahulu sebelum dicari di index.
    """
    key = stemmer.stem(term.lower())
    return set(inverted_index.get(key, []))


# Query 1: ("manajemen" AND "energi") AND "efisiensi"
p_manajemen = get_posting('manajemen')
p_energi    = get_posting('energi')
p_efisiensi = get_posting('efisiensi')

hasil_q1 = p_manajemen & p_energi & p_efisiensi

# Query 2: "konservasi" OR "efisiensi"
p_konservasi = get_posting('konservasi')

hasil_q2 = p_konservasi | p_efisiensi


def sort_doc(doc_set):
    return sorted(doc_set, key=lambda x: int(x.split()[1]))


# Tampilkan hasil
br_rows = [
    {
        'Query'    : '("manajemen" AND "energi") AND "efisiensi"',
        'Operasi'  : 'AND (interseksi)',
        'Hasil'    : ', '.join(sort_doc(hasil_q1)) if hasil_q1 else 'Tidak ada hasil',
        'Jumlah'   : len(hasil_q1),
    },
    {
        'Query'    : '"konservasi" OR "efisiensi"',
        'Operasi'  : 'OR (gabungan)',
        'Hasil'    : ', '.join(sort_doc(hasil_q2)),
        'Jumlah'   : len(hasil_q2),
    },
]

df_boolean = pd.DataFrame(br_rows)
df_boolean

,Query,Operasi,Hasil,Jumlah
0,"(""manajemen"" AND ""energi"") AND ""efisiensi""",AND (interseksi),"Doc 2, Doc 3, Doc 4, Doc 10, Doc 25, Doc 27, Doc 32, Doc...",13
1,"""konservasi"" OR ""efisiensi""",OR (gabungan),"Doc 2, Doc 3, Doc 4, Doc 10, Doc 15, Doc 25, Doc 27, Doc...",14

## 11. Incidence Matrix (TF-Biner)

In [19]:
query_terms = ['manajemen', 'energi', 'efisiensi', 'konservasi', 'transisi']
query_stems = [stemmer.stem(t) for t in query_terms]

matrix_rows = []
for rec in records:
    row = {'DocID': rec['DocID']}
    for term_raw, term_stem in zip(query_terms, query_stems):
        row[term_raw] = 1 if term_stem in rec['Stemming'] else 0
    matrix_rows.append(row)

df_matrix = pd.DataFrame(matrix_rows).set_index('DocID')

print('Incidence Matrix (TF-Biner) - 5 term kunci')
print(f'Total dokumen: {len(df_matrix)}')
df_matrix

Incidence Matrix (TF-Biner) - 5 term kunci
Total dokumen: 58

        manajemen  energi  efisiensi  konservasi  transisi
DocID
Doc 1           1       1          0           0         0
Doc 2           1       1          1           0         0
Doc 3           1       1          1           0         1
Doc 4           1       1          1           0         0
Doc 5           1       1          0           0         0
Doc 6           1       1          0           0         0
Doc 7           1       1          0           0         0
Doc 8           1       1          0           0         0
Doc 9           1       1          0           0         0
Doc 10          1       1          1           0         0
Doc 11          1       1          0           0         0
Doc 12          1       1          0           0         0
Doc 13          1       1          0           0         0
Doc 14          1       1          0           0         0
Doc 15          1       1          0           1         0
Doc 16          1       1          0           0         0
Doc 17          1       1          0           0         0
Doc 18          1       1          0           0         0
Doc 19          1       1          0           0         0
Doc 20          1       1          0           0         0
Doc 21          1       1          0           0         0
Doc 22          1       1          0           0         0
Doc 23          1       1          0           0         0
Doc 24          1       1          0           0         0
Doc 25          1       1          1           1         0
Doc 26          1       1          0           0         0
Doc 27          1       1          1           0         0
Doc 28          1       1          0           0         0
Doc 29          1       1          0           0         0
Doc 30          1       1          0           0         0
Doc 31          1       1          0           0         0
Doc 32          1       1          1           0         0
Doc 33          1       1          1           0         0
Doc 34          1       1          1           0         0
Doc 35          1       1          1           0         0
Doc 36          1       1          0           0         0
Doc 37          1       1          0           0         0
Doc 38          1       1          0           0         0
Doc 39          1       1          0           0         0
Doc 40          1       1          0           0         0
Doc 41          1       1          0           0         0
Doc 42          1       1          0           0         0
Doc 43          1       1          0           0         0
Doc 44          1       1          0           0         0
Doc 45          1       1          0           0         0
Doc 46          1       1          1           0         0
Doc 47          1       1          0           0         0
Doc 48          1       1          0           0         0
Doc 49          1       1          0           0         0
Doc 50          1       1          0           0         0
Doc 51          1       1          0           0         0
Doc 52          1       1          0           0         0
Doc 53          1       1          1           0         0
Doc 54          1       1          0           0         0
Doc 55          1       1          0           0         0
Doc 56          1       1          1           0         0
Doc 57          1       1          0           0         0
Doc 58          1       1          0           0         0

## 12. Simpan Semua Tabel ke Excel

In [20]:
output_file = 'IR_ManajemenEnergi_Output.xlsx'

with pd.ExcelWriter(output_file, engine='openpyxl') as writer:

    df_display[['DocID', 'Teks Mentah', 'Case Folding',
                'Tokenisasi', 'Stopword Removal', 'Stemming']].to_excel(
        writer, sheet_name='Preprocessing', index=False
    )

    df_forward.to_excel(
        writer, sheet_name='Forward Index', index=False
    )

    df_inverted.to_excel(
        writer, sheet_name='Inverted Index', index=False
    )

    df_boolean.to_excel(
        writer, sheet_name='Boolean Retrieval', index=False
    )

    df_matrix.to_excel(
        writer, sheet_name='Incidence Matrix'
    )

print(f'File disimpan: {output_file}')

File disimpan: IR_ManajemenEnergi_Output.xlsx

## 13. TF-IDF dan Vector Space Model (VSM)

In [21]:
import math

def calculate_tf_idf(records, inverted_index):
    """
    Menghitung bobot TF-IDF untuk setiap term di setiap dokumen.
    """
    tf_idf_scores = defaultdict(dict)
    num_documents = len(records)

    # Menghitung IDF (Inverse Document Frequency)
    idf_scores = {}
    for term, posting_list in inverted_index.items():
        df = len(posting_list) # Frekuensi Dokumen
        idf_scores[term] = math.log10(num_documents / (df + 1))

    # Menghitung TF-IDF
    for record in records:
        doc_id = record['DocID']
        stemmed_terms = record['Stemming']
        term_freq = defaultdict(int)
        for term in stemmed_terms:
            term_freq[term] += 1

        for term in set(stemmed_terms):
            tf = term_freq[term] / len(stemmed_terms)
            idf = idf_scores.get(term, 0)
            tf_idf_scores[doc_id][term] = tf * idf

    return tf_idf_scores, idf_scores

tf_idf_doc_scores, idf_scores = calculate_tf_idf(records, inverted_index)

print("Contoh TF-IDF untuk Doc 1:")
for term, score in list(tf_idf_doc_scores['Doc 1'].items())[:5]: # Menampilkan 5 term pertama dari Doc 1
    print(f"  {term}: {score:.4f}")

# Menyiapkan data untuk tampilan DataFrame
tfidf_rows = []
for doc_id, terms in tf_idf_doc_scores.items():
    sorted_terms = sorted(terms.items(), key=lambda item: item[1], reverse=True)
    tfidf_rows.append({
        'DocID': doc_id,
        'TF-IDF Scores': ', '.join([f'{t}:{s:.4f}' for t, s in sorted_terms])
    })

df_tfidf = pd.DataFrame(tfidf_rows)
df_tfidf.head()

Contoh TF-IDF untuk Doc 1:
  teliti: 0.0694
  akuntansi: 0.0835
  manajemen: -0.0007
  energi: -0.0007
  lingkung: 0.0694

   DocID                                                TF-IDF Scores
0  Doc 1  mediator:0.1329, dampak:0.1329, eksplorasi:0.1329, tuju:...
1  Doc 2  tinggi:0.1329, cenderung:0.1329, anggap:0.1329, usaha:0....
2  Doc 3  efisiensi:0.1157, murni:0.0914, transisi:0.0914, sedang:...
3  Doc 4  jamin:0.1072, sisi:0.0968, beri:0.0968, kualitas:0.0821,...
4  Doc 5  bantu:0.1072, karyawan:0.1072, sedia:0.1072, langgan:0.1...

In [22]:
def calculate_cosine_similarity(query_vector, document_vector):
    """
    Menghitung kesamaan kosinus antara dua vektor.
    """
    dot_product = sum(query_vector.get(term, 0) * document_vector.get(term, 0) for term in set(query_vector) | set(document_vector))

    magnitude_query = math.sqrt(sum(q_val**2 for q_val in query_vector.values()))
    magnitude_document = math.sqrt(sum(d_val**2 for d_val in document_vector.values()))

    if magnitude_query == 0 or magnitude_document == 0:
        return 0
    return dot_product / (magnitude_query * magnitude_document)

def query_vsm(query_text, tf_idf_doc_scores, idf_scores, records, stemmer, stopwords):
    """
    Mencari dokumen berdasarkan kueri menggunakan VSM dan kesamaan kosinus.
    """
    # 1. Preprocessing kueri
    processed_query = preprocessing('Query', query_text)
    query_stemmed_terms = processed_query['Stemming']

    # 2. Menghitung TF untuk kueri
    query_tf = defaultdict(int)
    for term in query_stemmed_terms:
        query_tf[term] += 1

    # 3. Menghitung TF-IDF untuk kueri
    query_tf_idf = {}
    if len(query_stemmed_terms) > 0:
        for term in set(query_stemmed_terms):
            tf = query_tf[term] / len(query_stemmed_terms)
            idf = idf_scores.get(term, 0)
            query_tf_idf[term] = tf * idf

    # 4. Menghitung kesamaan kosinus antara kueri dan setiap dokumen
    similarities = {}
    for doc_id, doc_tf_idf_vector in tf_idf_doc_scores.items():
        similarity = calculate_cosine_similarity(query_tf_idf, doc_tf_idf_vector)
        if similarity > 0:
            similarities[doc_id] = similarity

    # 5. Mengurutkan dokumen berdasarkan kesamaan
    ranked_documents = sorted(similarities.items(), key=lambda item: item[1], reverse=True)

    return ranked_documents

query = "Kebutuhan energi saat ini meningkat pesat"
ranked_docs = query_vsm(query, tf_idf_doc_scores, idf_scores, records, stemmer, STOPWORDS)

print(f"Dokumen yang relevan untuk kueri '{query}':")
if ranked_docs:
    for doc_id, score in ranked_docs[:10]:
        original_text = next((rec['Teks Mentah'] for rec in records if rec['DocID'] == doc_id), 'N/A')
        print(f"  {doc_id} (Similarity: {score:.4f}): {original_text[:100]}...")
else:
    print("Tidak ada dokumen yang relevan ditemukan.")

Dokumen yang relevan untuk kueri 'Kebutuhan energi saat ini meningkat pesat':
  Doc 51 (Similarity: 0.2659): Dengan demikian, manajemen energi tidak hanya menjawab tantangan peningkatan kebutuhan listrik, teta...
  Doc 37 (Similarity: 0.2245): Data ini berfungsi sebagai indikator penting untuk melihat sejauh mana kebutuhan energi listrik masy...
  Doc 36 (Similarity: 0.2088): Dalam konteks ini, pemahaman terhadap konsumsi listrik per kapita menjadi sangat relevan untuk melih...
  Doc 43 (Similarity: 0.1062): Salah satu langkah awal dalam menerapkan manajemen energi adalah peningkatan literasi energi masyara...
  Doc 56 (Similarity: 0.1055): Efisiensi penggunaan energi masih mungkin ditingkatkan melalui penerapan sistem manajemen energi ter...
  Doc 53 (Similarity: 0.1055): Efisiensi penggunaan energimasih mungkin ditingkatkan melalui penerapan sistem manajemen energi....
  Doc 24 (Similarity: 0.0988): Kegiatan ini dapat meningkatkan kemampuan peserta dalam melakukan audit dan manajemen energi dari ya...
  Doc 12 (Similarity: 0.0953): Berdasarkan UMKM di Jawa Timur, akuntansi hijau dan manajemen energi dapat meningkatkan kinerja UMKM...
  Doc 27 (Similarity: 0.0870): Penelitian ini bertujuan untuk mengkaji peran manajemen energi dalam meningkatkan efisiensi konsumsi...
  Doc 2 (Similarity: 0.0792): Penelitian sebelumnya menunjukkan bahwa ketika efisiensi energi dianggap strategis, perusahaan cende...

In [23]:
output_file = 'IR_ManajemenEnergi_Output.xlsx'

# Result
df_vsm_results = pd.DataFrame(ranked_docs, columns=['DocID', 'Similarity Score'])

with pd.ExcelWriter(output_file, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    df_tfidf.to_excel(
        writer, sheet_name='TF-IDF Scores', index=False
    )
    df_vsm_results.to_excel(
        writer, sheet_name='VSM Query Results', index=False
    )

print(f'TF-IDF scores and VSM query results {output_file}')

TF-IDF scores and VSM query results IR_ManajemenEnergi_Output.xlsx